// Types for function parameters
export interface GetP2pkhAddressParams {
    publicKeyBytes: Uint8Array;
    network: string;
}

export interface GetTaprootAddressParams {
    internalPublicKeyBytes: Uint8Array;
    tapTreeLeaves?: any; // Optional, can be null/undefined
    network: string;
}

export interface GetMultisigAddressParams {
    m: number;
    publicKeys: Uint8Array[];
    network: string;
    addressType: 'p2sh' | 'p2wsh';
}

export interface GetCollateralOutputScriptParams {
    arbitratorXOnlyPubkeys: Uint8Array[];
    mQuorum: number;
    userInternalXOnlyPubkeyBytes: Uint8Array;
}

export interface SignPsbtParams {
    psbtBase64: string;
    signRequests: any; // Specific type for signature requests
}

export interface FinalizePsbtParams {
    psbtBase64: string;
}

export interface ExtractTransactionParams {
    psbtBase64: string;
}

// Import initialization function and types from generated Wasm
import {
    getP2pkhAddress as getP2pkhAddressWasm,
    getTaprootAddress as getTaprootAddressWasm,
    getMultisigAddress as getMultisigAddressWasm,
    getCollateralOutputScript as getCollateralOutputScriptWasm,
    signPsbt as signPsbtWasm,
    finalizePsbt as finalizePsbtWasm,
    extractTransaction as extractTransactionWasm,
    // Add other Rust exported functions here
} from './pkg_wasm/pls_bitcoin_wasm'; // Path to JS generated by wasm-pack

// Variable to store initialization state
let wasmInitialized = false;

// Asynchronous initialization function for Wasm module
async function initializeWasm() {
    if (!wasmInitialized) {
        // WASM is automatically initialized when imported
        wasmInitialized = true;
    }
}

// Refactored functions to use parameter objects
export async function getP2pkhAddress(params: GetP2pkhAddressParams): Promise<string> {
    await initializeWasm();
    return getP2pkhAddressWasm(params.publicKeyBytes, params.network);
}

export async function getTaprootAddress(params: GetTaprootAddressParams): Promise<string> {
    await initializeWasm();
    return getTaprootAddressWasm(params.internalPublicKeyBytes, params.tapTreeLeaves, params.network);
}

export async function getMultisigAddress(params: GetMultisigAddressParams): Promise<string> {
    await initializeWasm();
    return getMultisigAddressWasm(params.m, params.publicKeys, params.network, params.addressType);
}

export async function getCollateralOutputScript(params: GetCollateralOutputScriptParams): Promise<Uint8Array> {
    await initializeWasm();
    return getCollateralOutputScriptWasm(params.arbitratorXOnlyPubkeys, params.mQuorum, params.userInternalXOnlyPubkeyBytes);
}

export async function signPsbt(params: SignPsbtParams): Promise<string> {
    await initializeWasm();
    try {
        return await signPsbtWasm(params.psbtBase64, params.signRequests);
    } catch (error) {
        console.error("Error in signPsbtWasm:", error);
        throw error;
    }
}

export async function finalizePsbt(params: FinalizePsbtParams): Promise<string> {
    await initializeWasm();
    return finalizePsbtWasm(params.psbtBase64);
}

export async function extractTransaction(params: ExtractTransactionParams): Promise<string> {
    await initializeWasm();
    return extractTransactionWasm(params.psbtBase64);
}

// Convenience functions to maintain compatibility with old API
// @deprecated Use getP2pkhAddress with params object instead
export async function getP2pkhAddressLegacy(publicKeyBytes: Uint8Array, network: string): Promise<string> {
    return getP2pkhAddress({ publicKeyBytes, network });
}

// @deprecated Use getTaprootAddress with params object instead
export async function getTaprootAddressLegacy(
    internalPublicKeyBytes: Uint8Array,
    tapTreeLeavesJs: any,
    network: string
): Promise<string> {
    return getTaprootAddress({ internalPublicKeyBytes, tapTreeLeaves: tapTreeLeavesJs, network });
}

// @deprecated Use getMultisigAddress with params object instead
export async function getMultisigAddressLegacy(
    m: number,
    publicKeysJs: Uint8Array[],
    network: string,
    addressType: string
): Promise<string> {
    return getMultisigAddress({ m, publicKeys: publicKeysJs, network, addressType: addressType as 'p2sh' | 'p2wsh' });
}

// @deprecated Use getCollateralOutputScript with params object instead
export async function getCollateralOutputScriptLegacy(
    arbitratorXOnlyPubkeysJs: Uint8Array[],
    mQuorum: number,
    userInternalXOnlyPubkeyBytes: Uint8Array
): Promise<Uint8Array> {
    return getCollateralOutputScript({ arbitratorXOnlyPubkeys: arbitratorXOnlyPubkeysJs, mQuorum, userInternalXOnlyPubkeyBytes });
}

// @deprecated Use signPsbt with params object instead
export async function signPsbtLegacy(psbtBase64: string, signRequestsJs: any): Promise<string> {
    return signPsbt({ psbtBase64, signRequests: signRequestsJs });
}

// @deprecated Use finalizePsbt with params object instead
export async function finalizePsbtLegacy(psbtBase64: string): Promise<string> {
    return finalizePsbt({ psbtBase64 });
}

// @deprecated Use extractTransaction with params object instead
export async function extractTransactionLegacy(psbtBase64: string): Promise<string> {
    return extractTransaction({ psbtBase64 });
}

// Optional: Export initialization function if it needs to be called manually from outside.
export { initializeWasm };
